### ISSUE TITLE
Removing B9S

### ISSUE THREAD

**Issue by trilleplay** [SciresM/boot9strap#12]
So before i install boot9strap i want to make sure that i can remove it **safely** .
But there is no guide of how to do this.
So how can i do this **tested** methods would be preferred. 

Thanks!

**Comment by TuxSH** [comment]
This is not a b9s issue in any case.

Restore the firm backup made by SafeB9SInstaller using GM9.

**Comment by trilleplay** [comment]
Okay Thanks @TuxSH

**Comment by trilleplay** [comment]
Nope that bricked me.
Thanks for trying tho.

**Comment by trilleplay** [comment]
But i guess @TuxSH i'll just have to wait for MagnetHax.
This works on blue bootrom bricked consoles right?

**Comment by AuroraWright** [comment]
This has nothing to do with B9S itself. If you want to ask for a removal feature in the installer, ask in its repo, not here.
