### ISSUE TITLE
Suggestion: Pass loader name/version as arg to loaded firm

### ISSUE THREAD

**Issue by svanheulen** [SciresM/boot9strap#13]
I think it would be useful to have loaders/chainloaders pass a string with their name and version as an argument to the firm they load. Then the firm could display that information to the user (for instance in Luma3DS's config menu).

This was something that always annoyed me about A9LH. Not being able to see what version I had installed. This way you'll also be able to tell if you're running the official b9s or a fork or some other loader.

Obviously a change like this will effect lots of other software, but I figured this was the best place to bring it up.

**Comment by svanheulen** [comment]
Another idea, that would be less disruptive, is store the name/version string in the "reserved" section in FIRM header.
Edit: oh... I guess b9s already does that, but profi200 made the point that Nintendo could start using the reserved section if they wanted to mess with us.

**Comment by TuxSH** [comment]
See the value passed to r2 (for version).

**Comment by svanheulen** [comment]
@TuxSH But that doesn't tell us if it's b9s or a fork or a different loader. Luma3DS passed the same value (`0x2BEEF`) when it chainloads a firm. So it seem like you intended that to be more of an API version then to give any info about what software is doing the loading.
