### ISSUE TITLE
How do I check which version of B9S I have installed?

### ISSUE THREAD

**Issue by gingerbeardman** [SciresM/boot9strap#16]
Is there an easy way? Thanks

**Comment by pbanj** [comment]
put the newest luma's boot.firm on the root of your sd card. hold select and turn the system on, if the config screen says it's 8.1 you have b9s 1.2. if it doesnt boot or shows a different version you have b9s 1

**Comment by fr3quency** [comment]
Apparently they cannot read the links in the urlbar. :') Misreading GitHub for GBAtemp... You must have >9000 myopia.

**Comment by gingerbeardman** [comment]
I don't think "upgrade and if it breaks you're on the old B9S" is an easy way to just check what version I have installed.
