### ISSUE TITLE
A way of confirming that an ntrboot was successful on devices with B9S already installed

### ISSUE THREAD

**Issue by jason0597** [SciresM/boot9strap#17]
Some people have 2 3DSes, one that is working and CFW'd, and one that is bricked
They get a DS flashcart to unbrick their bricked 3DS, and use their working 3DS to flash their DS flashcart

But, when they try to boot from that DS flashcart on their bricked 3DS, they do not know if the DS flashcart wasn't flashed properly, or if their buttons are broken, or if their magnet isn't strong enough, since the bricked 3DS just remains as is with static black screens, not informing them of anything they might be doing wrong.

And they cannot use their CFW'd 3DS to check if they have flashed their DS flashcart properly, because even if they try to boot from their DS flashcart on their CFW'd 3DS, all that will happen in the end is just boot the boot.firm on their SD card. So they cannot know if the boot.firm on their SD card was booted by B9S on their DS flashcart, or the B9S on their NAND.

What can fix this is by adding a 1-2 second splash screen to the B9S for DS flashcarts, that simply prints to the screen a "BOOTED FROM NTRBOOT", to inform the user the ntrboothax was successful. 
Another fix is making the NTR version of B9S, able to boot only from ntrboot.firm instead of boot.firm, so that we can differentiate the two.

**Comment by urherenow** [comment]
All you need to do is NOT remove the magnet. If you used NTRBoot, the safeb9sinstaller screen will show up as soon as you let go of the buttons with the magnet still in place. If it didn't work, the screen will remain blank until removing the magnet. (and then either boot home menu or stay black if bricked, when you remove it). Very simple to check on the console you just used to set it all up with.

**Comment by jason0597** [comment]
You mean to say that the bootROM will just hang there on a black screen, waiting for you to remove the magnet, if it fails to find a correct SLOT-1 cartridge? At which point, the moment you remove the magnet, it will continue to boot from the NAND?

So you can detect if a ntrboothax failed, by checking to see if the 3DS hangs there and is waiting for you to remove the magnet?

**Comment by urherenow** [comment]
Yes. 

Disclaimer: I haven't checked this with anything other than safeboot9strapinstaller, and I custom built my ntrboot flasher to look for ntr_boot.firm, so luma was still on my card as boot.firm at the same time. Removing the magnet at the same time, or before, letting go of the buttons, boots me right to the home menu (luma). Let go of ONLY the buttons, and safeb9sinstaller menu comes up, with the magnet still in place (although you can remove the magnet at that point, so I'm told).

**Comment by jason0597** [comment]
Well I am trying to force-fail a ntrboothax on my O3DSXL (with B9S), and my 3DS refuses to turn on with just the magnet on it (not the start/select/x, just the magnet).
I inserted an unsupported and unflashed GW blue card

**Comment by Derek1199** [comment]
There is no reason to try making it fail.

**Comment by jason0597** [comment]
I am trying to make it fail so that I can see if urherenow is right, and confirm that there is no need for making the NTR version of B9S boot from ntrboot.firm instead of boot.firm

**Comment by TuxSH** [comment]
Given most people use Luma: https://github.com/AuroraWright/Luma3DS/commit/f79923814d371bb051afcb84b43e6dca3e271e2e

**Comment by urherenow** [comment]
to be fair, I custom built mine to use ntr_boot.firm anyway because it's much easier and less card swapping. I drag a pre-made folder to a card ONCE, and I'm done swapping. ntrboot loads safebootstrap9installer as ntr_boot.firm, and luma is there as boot.firm so immediately after b9s install, you're already booting into luma. Makes perfect sense to me. Just not for the chief complaint of this particular issue...

**Comment by jason0597** [comment]
I understand what you are trying to say urherenow. You mean to say that you are using a custom built ntr-boot9strap that boots from from ntr_boot.firm, and you use that custom made NTR-B9S to speed up the process of installing B9S to a virgin 3DS, essentially just extracting a ZIP that's pre-made and skipping a lot of steps, saving a lot of time.

However, this is completely irrelevant to the issue I have submitted. I have asked for a way to confirm a DS flashcart is properly flashed on a B9S'd system, not a way to install B9S on a virgin 3DS. And as I said in the original post, making the NTR vesion of B9S boot from ntrboot.firm instead of boot.firm would resolve this issue.

**Comment by urherenow** [comment]
Clearly, you DON'T understand. This isn't even an issue. You can already tell if it works or not, and I already explained how. Leave the magnet in place when you let go of start+select+X. The safeboot9strapinstaller menu will NOT show up with the magnet on if it didn't work (the screen will stay black until you remove the magnet). It WILL show up if it did (with the magnet still in place).

EDIT: welp. Moot point with TuxSH's Luma commit, I guess. Either way, this issue should be closed.

**Comment by jason0597** [comment]
I understood you in the 3rd post, no need to be rude.

If/When R4 SDHC RTS Lite supports comes, I will test it myself.

**Comment by NightScript370** [comment]
@TuxSH I'd rather it have it into B9S, as there are people who don't like Luma and stick to others.

**Comment by lunathir** [comment]
Do you have to flash the NTRBootHax to the card before the 3DS will boot into the DS game? Because I can't but I'm using a SCDS2+ so it's unflashed.

**Comment by SSQ123** [comment]
Not if it's supported by your system version and the files are in the correct directories. But I have an R4I 3DS RTS card, so internally they might be different. But just check it on a DS as Nintendo might've blocked it in the 11.6 firmware.

**Comment by jason0597** [comment]
closing as luma tells you your entrypoint now
