### ISSUE TITLE
How to know what B9S version it is on my 3DS?

### ISSUE THREAD

**Issue by JKC-A9LH** [SciresM/boot9strap#22]
Is there any way to know? How to tell B9S V1.2 from B9S V1.3?

**Comment by jupitteer** [comment]
No, there is not. There really isn't any reason to want to know, either; if safeb9sinstaller succeeded, you are on the version you updated to.

**Comment by fincs** [comment]
Yes, there is. Just read the value of r2 when your payload is executed, it will have different values depending on the version of b9s that is installed on the system. Currently afaik there are no ARM9 programs that actually show this information to the user.

**Comment by zoogie** [comment]
@fincs the problem is, luma's chainloader hardcodes the b9s version for some reason.
https://github.com/AuroraWright/Luma3DS/blob/master/chainloader/source/start.s#L59

sciresm actually has been putting the version at 0x3C in the b9s header. unfortunately, he forgot to update it on 1.3.

**Comment by MasterGamingYT** [comment]
There is now a script in godmode9 that tells you the version

**Comment by ermyril** [comment]
For a future lurkers - [this](https://github.com/16BitWonder/GodMode9-Scripts/blob/master/b9s_version.gm9) is the script @MasterGamingYT was talking about.
