### ISSUE TITLE
Use latest sdmmc.c driver for faster boot times

### ISSUE THREAD

**Issue by Nemris** [SciresM/boot9strap#28]
As stated by the fastboot3DS v1.1 stable changelog, `[boot times] have been vastly improved thanks to the new SDMMC.c driver`. I've tried to measure how effective this improvement really is, and the measurements show that Luma3DS boots in ~8.7s when using b9s, while taking ~8.2s with fb3DS.

Would it be possible to replace the current sdmmc.c driver used by b9s with this (apparently) faster variant?

**Comment by TuxSH** [comment]
I've observed a regression with it with luma.

**Comment by Nemris** [comment]
I'll leave the issue open just in case.

**Comment by Nemris** [comment]
Closing since the new commits indicate that you found an even better alternative. (Nice work.)
