### ISSUE TITLE
Boot9Strap Adding Unknown Titles to Sysnand?

### ISSUE THREAD

**Issue by DeadSkullzJr** [SciresM/boot9strap#29]
I decided to install Boot9Strap to my old 3DS running on 4.2 Sysnand (don't question me please). One thing I noticed that happened when installing Boot9Strap is a few extra icons pop up on my menu screen, I haven't had this issue occur on my other consoles, though those ran a much later firmware than this old console here. Here is a screenshot of the four titles that for whatever reason installed onto my console (mind you I didn't have any file manager/CIA installer, so I couldn't install these myself).
![image0](https://user-images.githubusercontent.com/26408949/58380481-84a04b00-7f66-11e9-8bf6-7faaabac76c8.jpg)

**Comment by ihaveamac** [comment]
No, boot9strap doesn’t do this. These titles already existed. Because you’re not using 9.0+, one of Luma3DS’s patches is exposing these hidden titles.

**Comment by TuxSH** [comment]
Update to 9.6 or above.
