### ISSUE TITLE
Suggestion: firmware launch failsafe.

### ISSUE THREAD

**Issue by miltoncandelero** [SciresM/boot9strap#4]
Would it be to hard to implement the bootloader a bit like this?

* Check for key combo to dump the bootroms
* Look for firm payload on sd
* Look for firm payload on ctrnand

And if everything fails, boot an "almost" unpatched vanilla sysnand.

That is, patch only the firm protection module and load the sysnand.

That way it looks unmodded but it is safe from updates deleting sighax.

It could be useful to hide sighax when sending the 3ds to tech support.

Thank your for your time and awesome work!

**Comment by AuroraWright** [comment]
Having it on ctrnand pretty much hides it eh :P
Also it's harder than it looks. You need to have the firm protection persist after firmlaunch or people can undo sighax, and so on.

**Comment by TuxSH** [comment]
It's not really b9s's job to do what people call CFW do...

And yeah, that:
> Having it on ctrnand pretty much hides it eh

**Comment by SciresM** [comment]
Closing, for now. Will consider something like this in the future...but I don't think it's b9s's job, honestly.
