### ISSUE TITLE
Unable to dump OTP or Bootrom

### ISSUE THREAD

**Issue by gnmmarechal** [SciresM/boot9strap#6]
Hey there, I am unable to dump them by holding START, SELECT and X on boot. I am on a 2DS, if that matters.

Nothing happens, nothing appears in the boot9strap directory. The buttons have been tested, and work fine.

**Comment by GabrielRRussell** [comment]
Hold the buttons before turning it on. I know this sounds stupid, but maybe you're just pressing them too late.

**Comment by gnmmarechal** [comment]
I did that. Still, nothing happens.

**Comment by TuxSH** [comment]
Can you boot `boot.firm` from the SD card. If anything, remove that file and see if it takes a longer time to shutdown with start+select+X pressed.

**Comment by gnmmarechal** [comment]
Yep, I can boot from it. I'm going to try that, then.

**Comment by gnmmarechal** [comment]
It seems to have properly dumped the files. I've removed both SD:/boot.firm and CTRNAND:/boot.firm .

**Comment by gnmmarechal** [comment]
I suppose this can be closed?
