### ISSUE TITLE
Can't acces to SysNand

### ISSUE THREAD

**Issue by chronoss09** [SciresM/boot9strap#9]
After installed the last boot9strap, i can't acces to my sysnand with Luma 8.0

"An exception occurred
Processor : ARM9
Exception type : data abort"
and many line with R0, R2......

Can you help me please ?

**Comment by Tonogata** [comment]
I'm having the same issue as well with my 2ds

**Comment by GabrielRRussell** [comment]
This sounds like a Luma problem. Can you boot payloads? You can try to restore an old boot9strap firm.

**Comment by TuxSH** [comment]
Update GM9, etc. with their latest releases.
